# A lot of dictionaries stored into a list
question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "medium",
     "question": "Vincent van Gogh cut off one of his ears.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "EDM label Monstercat signs tracks instead of artists.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The scientific name for the Southern Lights is Aurora Australis?", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
     "question": "You can tell the age of a ladybird by counting the spots on his back.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Avatar: The Last Airbender&quot; and &quot;The Legend of Korra&quot;, Lavabending is a specialized bending technique of Firebending.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
